baseURL = "https://Cola1605.github.io/System_News"
title = "Blog của Khoa"
languageCode = "vi"

theme = "Mainroad"
disqusShortname = ""
googleAnalytics = ""

[Author]
  name = "Cola1605"
  bio = "Chuyên gia về AI, lập trình và công nghệ. Chia sẻ kiến thức và kinh nghiệm thực tế."
  avatar = "img/avatar.png"

[Params]
  description = "Blog cá nhân chia sẻ kiến thức về lập trình, AI và công nghệ."
  opengraph = true
  twitter_cards = false
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["posts"]

[Params.logo]
  subtitle = "AI & Technology Blog"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[pagination]
  pagerSize = 10
canonifyURLs = true
relativeURLs = false
uglyURLs = false

# Force absolute URLs everywhere
[params]
  baseURL = "https://Cola1605.github.io/System_News"

[[menu.main]]
  name = "Trang chủ"
  url = "/System_News/"
  weight = 10

[[menu.main]]
  name = "Bài viết"
  url = "/System_News/posts/"
  weight = 20

[[menu.main]]
  name = "Giới thiệu"
  url = "/System_News/about/"
  weight = 30
